version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@172.18.3.34:1521/XE
      SPRING_DATASOURCE_USERNAME: EQUIPE3_DEV
      SPRING_DATASOURCE_PASSWORD: equipe3_dev
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: oracle.jdbc.OracleDriver
    ports:
      - "8080:8080"
    restart: on-failure

  frontend:
    build:
      context: ../csci-evae-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
volumes:
  mysql-data:


