REM 
REM Cr�ation Utilisateur DOSI1
REM

drop user DOSI1 cascade;

create user DOSI1 identified by dosi account unlock;
ALTER USER DOSI1 DEFAULT ROLE ALL;
GRANT UNLIMITED TABLESPACE TO DOSI1;
grant CONNECT,RESOURCE to DOSI1;
GRANT CREATE TABLE TO DOSI1;
GRANT CREATE VIEW TO DOSI1;          
GRANT CREATE PROCEDURE TO DOSI1;                	 
GRANT CREATE SYNONYM TO DOSI1;                  
GRANT CREATE SEQUENCE TO DOSI1;                	 
GRANT CREATE TRIGGER TO DOSI1;
GRANT CREATE TYPE TO DOSI1;
GRANT SELECT ON dba_rollback_segs TO DOSI1;            
GRANT SELECT ON dba_segments TO DOSI1;
