REM INSERTING into     DROIT
SET DEFINE OFF;
Insert into     DROIT (ID_EVALUATION,NO_ENSEIGNANT,CONSULTATION,DUPLICATION) values ('1','3','O','O');
Insert into     DROIT (ID_EVALUATION,NO_ENSEIGNANT,CONSULTATION,DUPLICATION) values ('1','4','O','O');
Insert into     DROIT (ID_EVALUATION,NO_ENSEIGNANT,CONSULTATION,DUPLICATION) values ('2','3','O','N');
Insert into     DROIT (ID_EVALUATION,NO_ENSEIGNANT,CONSULTATION,DUPLICATION) values ('1','2','O','O');
Insert into     DROIT (ID_EVALUATION,NO_ENSEIGNANT,CONSULTATION,DUPLICATION) values ('3','1','O','O');
Insert into     DROIT (ID_EVALUATION,NO_ENSEIGNANT,CONSULTATION,DUPLICATION) values ('4','1','O','O');
Insert into     DROIT (ID_EVALUATION,NO_ENSEIGNANT,CONSULTATION,DUPLICATION) values ('5','1','O','O');
Insert into     DROIT (ID_EVALUATION,NO_ENSEIGNANT,CONSULTATION,DUPLICATION) values ('3','2','O','O');
Insert into     DROIT (ID_EVALUATION,NO_ENSEIGNANT,CONSULTATION,DUPLICATION) values ('5','2','O','O');
Insert into     DROIT (ID_EVALUATION,NO_ENSEIGNANT,CONSULTATION,DUPLICATION) values ('6','2','O','O');
