REM INSERTING into      ELEMENT_CONSTITUTIF
SET DEFINE OFF;
Insert into      ELEMENT_CONSTITUTIF (CODE_FORMATION,CODE_UE,CODE_EC,NO_ENSEIGNANT,DESIGNATION,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) values ('M2DOSI','PCO','ERP','6','Integration de progiciels',null,'6','6','6');
Insert into      ELEMENT_CONSTITUTIF (CODE_FORMATION,CODE_UE,CODE_EC,NO_ENSEIGNANT,DESIGNATION,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) values ('M2DOSI','PCO','SFM','1','Stage en France pre-embauche Maroc','Preparation au stage en France dans une perspective dembauche au Maroc','6','6','6');
Insert into      ELEMENT_CONSTITUTIF (CODE_FORMATION,CODE_UE,CODE_EC,NO_ENSEIGNANT,DESIGNATION,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) values ('M2DOSI','J2EE','CME','2','Couche Metier','EJB,REST et JPA','12','12','12');
Insert into      ELEMENT_CONSTITUTIF (CODE_FORMATION,CODE_UE,CODE_EC,NO_ENSEIGNANT,DESIGNATION,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) values ('M2DOSI','J2EE','CPR','4','Couche Presentation','SPRING MVC','4','4','4');
