REM INSERTING into  RUBRIQUE
SET DEFINE OFF;
Insert into  RUBRIQUE (ID_RUBRIQUE,TYPE,NO_ENSEIGNANT,DESIGNATION,ORDRE) values ('1','RBS',null,'COURS','1');
Insert into  RUBRIQUE (ID_RUBRIQUE,TYPE,NO_ENSEIGNANT,DESIGNATION,ORDRE) values ('2','RBS',null,'COURS/TD','2');
Insert into  RUBRIQUE (ID_RUBRIQUE,TYPE,NO_ENSEIGNANT,DESIGNATION,ORDRE) values ('3','RBS',null,'TD','3');
Insert into  RUBRIQUE (ID_RUBRIQUE,TYPE,NO_ENSEIGNANT,DESIGNATION,ORDRE) values ('4','RBS',null,'TD/TP','4');
Insert into  RUBRIQUE (ID_RUBRIQUE,TYPE,NO_ENSEIGNANT,DESIGNATION,ORDRE) values ('5','RBS',null,'TP','5');
Insert into  RUBRIQUE (ID_RUBRIQUE,TYPE,NO_ENSEIGNANT,DESIGNATION,ORDRE) values ('6','RBS',null,'PROJET','6');
Insert into  RUBRIQUE (ID_RUBRIQUE,TYPE,NO_ENSEIGNANT,DESIGNATION,ORDRE) values ('7','RBS',null,'BILAN','7');
Insert into  RUBRIQUE (ID_RUBRIQUE,TYPE,NO_ENSEIGNANT,DESIGNATION,ORDRE) values ('8','RBS',null,'CM pre-compose','8');
