REM INSERTING into    UNITE_ENSEIGNEMENT
SET DEFINE OFF;
Insert into    UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) values ('M2DOSI','ISI','1','Ingenierie des Systemes dInformation','9  ',null,'20','20','20');
Insert into    UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) values ('M2DOSI','IDL','1','Ingenierie de Developpement Logiciel','9  ',null,'20','20','20');
Insert into    UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) values ('M2DOSI','J2EE','2','Java/J2EE','9  ',null,'20','20','20');
Insert into    UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) values ('M2DOSI','SR','2','Systemes Repartis','10 ',null,'20','20','20');
Insert into    UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) values ('M2DOSI','EDE','3','Environnement de Developpement','9  ',null,'0','0','48');
Insert into    UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) values ('M2DOSI','WEB','3','Langages du WEB','9  ',null,'20','20','20');
Insert into    UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) values ('M2DOSI','CO','5','Conception Objet','9  ',null,'20','20','20');
Insert into    UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) values ('M2DOSI','PCO','2','Preparation au Contexte de lOffshore','10 ',null,'16','16','16');
Insert into    UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) values ('M2DOSI','BI','5','Business Intelligence','10 ',null,'18','16','20');
Insert into    UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) values ('M2DOSI','ERP','1','Enterprise resource planning','8  ',null,'16','16','16');
Insert into    UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) values ('M2DOSI','SW','2','Service Web','10 ',null,'18','18','18');
