--
--  Création du jeu d'essai de la table UNITE_ENSEIGNEMENT
--


Insert into    UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) values ('M2DOSI','BI','5','Business Intelligence','10 ',null,'18','16','20');

Insert into    UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) values ('M2DOSI','ERP','1','Enterprise resource planning','8  ',null,'16','16','16');

Insert into    UNITE_ENSEIGNEMENT (CODE_FORMATION,CODE_UE,NO_ENSEIGNANT,DESIGNATION,SEMESTRE,DESCRIPTION,NBH_CM,NBH_TD,NBH_TP) values ('M2DOSI','SW','2','Service Web','10 ',null,'18','18','18');
