-- 
-- Script d'installation du CSCI-EVAE
-- Ph. Saliou - 17 janvier 2014
--	

-- Cr�ation des �l�ments DDL :  tables, vues, index, ...
@@01-CREATION/01-DDL/csci_evae_tab
@@01-CREATION/01-DDL/csci_evae_vw
@@01-CREATION/01-DDL/csci_evae_pk
@@01-CREATION/01-DDL/csci_evae_uk
@@01-CREATION/01-DDL/csci_evae_fk
@@01-CREATION/01-DDL/csci_evae_ck
@@01-CREATION/01-DDL/csci_evae_ind
@@01-CREATION/01-DDL/csci_evae_seq
@@01-CREATION/01-DDL/csci_evae_avt

-- Cr�ation de l'API de la table EVALUATION
@@01-CREATION/02-API/EVE.PKS
@@01-CREATION/02-API/EVE.PKB
@@01-CREATION/02-API/EVE.TRG

-- Cr�ation de l'API de la table QUALIFICATIF
@@01-CREATION/02-API/QUA.PKS
@@01-CREATION/02-API/QUA.PKB
@@01-CREATION/02-API/QUA.TRG

-- Cr�ation de l'API de la table QUESTION
@@01-CREATION/02-API/QUE.PKS
@@01-CREATION/02-API/QUE.PKB
@@01-CREATION/02-API/QUE.TRG

-- Cr�ation de l'API de la table QUESTION_EVALUATION
@@01-CREATION/02-API/QEV.PKS
@@01-CREATION/02-API/QEV.PKB
@@01-CREATION/02-API/QEV.TRG

-- Cr�ation de l'API de la table REPONSE_EVALUATION
@@01-CREATION/02-API/RPE.PKS
@@01-CREATION/02-API/RPE.PKB
@@01-CREATION/02-API/RPE.TRG

-- Cr�ation de l'API de la table RUBRIQUE
@@01-CREATION/02-API/RUB.PKS
@@01-CREATION/02-API/RUB.PKB
@@01-CREATION/02-API/RUB.TRG

-- Cr�ation de l'API de la table RUBRIQUE_EVALUATION
@@01-CREATION/02-API/REV.PKS
@@01-CREATION/02-API/REV.PKB
@@01-CREATION/02-API/REV.TRG

-- Cr�ation du jeu d'essai
@@02-JEU-ESSAI/QUALIFICATIF
@@02-JEU-ESSAI/QUESTION
@@02-JEU-ESSAI/RUBRIQUE
@@02-JEU-ESSAI/RUBRIQUE_QUESTION
@@02-JEU-ESSAI/EVALUATION
@@02-JEU-ESSAI/DROIT
@@02-JEU-ESSAI/RUBRIQUE_EVALUATION
@@02-JEU-ESSAI/QUESTION_EVALUATION
@@02-JEU-ESSAI/REPONSE_EVALUATION
@@02-JEU-ESSAI/REPONSE_QUESTION


commit;
