--
-- Cr�ation des tables de l'article de configuration CSCI_ADM
--

PROMPT Creating Table 'ETUDIANT'
CREATE TABLE ETUDIANT
 (NO_ETUDIANT VARCHAR2(50) NOT NULL
 ,CODE_FORMATION VARCHAR2(8) NOT NULL
 ,ANNEE_UNIVERSITAIRE VARCHAR2(10) NOT NULL
 ,NOM VARCHAR2(50) NOT NULL
 ,PRENOM VARCHAR2(50) NOT NULL
 ,SEXE VARCHAR2(1) NOT NULL
 ,DATE_NAISSANCE DATE NOT NULL
 ,LIEU_NAISSANCE VARCHAR2(255) NOT NULL
 ,NATIONALITE VARCHAR2(50) DEFAULT 'Fran�aise' NOT NULL
 ,TELEPHONE VARCHAR2(20)
 ,MOBILE VARCHAR2(20)
 ,EMAIL VARCHAR2(255) NOT NULL
 ,EMAIL_UBO VARCHAR2(255)
 ,ADRESSE VARCHAR2(255) NOT NULL
 ,CODE_POSTAL VARCHAR2(10)
 ,VILLE VARCHAR2(255) NOT NULL
 ,PAYS_ORIGINE VARCHAR2(5) NOT NULL
 ,UNIVERSITE_ORIGINE VARCHAR2(6) NOT NULL
 ,GROUPE_TP NUMBER
 ,GROUPE_ANGLAIS NUMBER
 )
/


PROMPT Creating Table 'ENSEIGNANT'
CREATE TABLE ENSEIGNANT
 (NO_ENSEIGNANT NUMBER(5) NOT NULL
 ,TYPE VARCHAR2(5) NOT NULL
 ,SEXE VARCHAR2(1) NOT NULL
 ,NOM VARCHAR2(50) NOT NULL
 ,PRENOM VARCHAR2(50) NOT NULL
 ,ADRESSE VARCHAR2(255) NOT NULL
 ,CODE_POSTAL VARCHAR2(10) NOT NULL
 ,VILLE VARCHAR2(255) NOT NULL
 ,PAYS VARCHAR2(5) NOT NULL
 ,MOBILE VARCHAR2(20) NOT NULL
 ,TELEPHONE VARCHAR2(20)
 ,EMAIL_UBO VARCHAR2(255) NOT NULL
 ,EMAIL_PERSO VARCHAR2(255)
 )
/



PROMPT Creating Table 'PROMOTION'
CREATE TABLE PROMOTION
 (CODE_FORMATION VARCHAR2(8) NOT NULL
 ,ANNEE_UNIVERSITAIRE VARCHAR2(10) NOT NULL
 ,NO_ENSEIGNANT NUMBER(5)
 ,SIGLE_PROMOTION VARCHAR2(16)
 ,NB_MAX_ETUDIANT NUMBER(3) NOT NULL
 ,DATE_REPONSE_LP DATE
 ,DATE_REPONSE_LALP DATE
 ,DATE_RENTREE DATE
 ,LIEU_RENTREE VARCHAR2(12) DEFAULT 'LC117A'
 ,PROCESSUS_STAGE VARCHAR2(5) DEFAULT 'RECH'
 ,COMMENTAIRE VARCHAR2(255)
 )
/



PROMPT Creating Table 'ELEMENT_CONSTITUTIF'
CREATE TABLE ELEMENT_CONSTITUTIF
 (CODE_FORMATION VARCHAR2(8) NOT NULL
 ,CODE_UE VARCHAR2(8) NOT NULL
 ,CODE_EC VARCHAR2(8) NOT NULL
 ,NO_ENSEIGNANT NUMBER(5) NOT NULL
 ,DESIGNATION VARCHAR2(64) NOT NULL
 ,DESCRIPTION VARCHAR2(240)
 ,NBH_CM NUMBER(2)
 ,NBH_TD NUMBER(2)
 ,NBH_TP NUMBER(2)
 )
/


PROMPT Creating Table 'CANDIDAT'
CREATE TABLE CANDIDAT
 (NO_CANDIDAT VARCHAR2(50) NOT NULL
 ,CODE_FORMATION VARCHAR2(8) NOT NULL
 ,ANNEE_UNIVERSITAIRE VARCHAR2(10) NOT NULL
 ,NOM VARCHAR2(50) NOT NULL
 ,PRENOM VARCHAR2(50) NOT NULL
 ,SEXE VARCHAR2(1) NOT NULL
 ,DATE_NAISSANCE DATE NOT NULL
 ,LIEU_NAISSANCE VARCHAR2(255) NOT NULL
 ,NATIONALITE VARCHAR2(50) DEFAULT 'Fran�aise' NOT NULL
 ,TELEPHONE VARCHAR2(20)
 ,MOBILE VARCHAR2(20)
 ,EMAIL VARCHAR2(255) NOT NULL
 ,ADRESSE VARCHAR2(255) NOT NULL
 ,CODE_POSTAL VARCHAR2(10)
 ,VILLE VARCHAR2(255) NOT NULL
 ,PAYS_ORIGINE VARCHAR2(5) NOT NULL
 ,UNIVERSITE_ORIGINE VARCHAR2(6) NOT NULL
 ,LISTE_SELECTION VARCHAR2(6)
 ,SELECTION_NO_ORDRE NUMBER
 ,CONFIRMATION_CANDIDAT CHAR(1)
 ,DATE_REPONSE_CANDIDAT DATE
 )
/



PROMPT Creating Table 'UNITE_ENSEIGNEMENT'
CREATE TABLE UNITE_ENSEIGNEMENT
 (CODE_FORMATION VARCHAR2(8) NOT NULL
 ,CODE_UE VARCHAR2(8) NOT NULL
 ,NO_ENSEIGNANT NUMBER(5) NOT NULL
 ,DESIGNATION VARCHAR2(64) NOT NULL
 ,SEMESTRE CHAR(3) NOT NULL
 ,DESCRIPTION VARCHAR2(256)
 ,NBH_CM INTEGER
 ,NBH_TD NUMBER(2)
 ,NBH_TP NUMBER(2)
 )
/


PROMPT Creating Table 'FORMATION'
CREATE TABLE FORMATION
 (CODE_FORMATION VARCHAR2(8) NOT NULL
 ,DIPLOME VARCHAR2(3) NOT NULL
 ,N0_ANNEE NUMBER(1) DEFAULT 1 NOT NULL
 ,NOM_FORMATION VARCHAR2(64) NOT NULL
 ,DOUBLE_DIPLOME CHAR(1) NOT NULL
 ,DEBUT_ACCREDITATION DATE
 ,FIN_ACCREDITATION DATE
 )
/


