--
--  Création du jeu d'essai de la table AUTHENTIFICATION
--

INSERT INTO DOSI1.AUTHENTIFICATION (ID_CONNECTION, ROLE, LOGIN_CONNECTION, PSEUDO_CONNECTION, MOT_PASSE, NO_ENSEIGNANT, NO_ETUDIANT) VALUES (22, 'ETU', 'mohamed.elheddadi@univ-brest.fr', 'mohamedetu', 'dosi', null, '21406398');

INSERT INTO DOSI1.AUTHENTIFICATION (ID_CONNECTION, ROLE, LOGIN_CONNECTION, PSEUDO_CONNECTION, MOT_PASSE, NO_ENSEIGNANT, NO_ETUDIANT) VALUES (21, 'ADM', 'michel.ga@univ-brest.fr', 'micheladm', 'dosi', null, null);

INSERT INTO DOSI1.AUTHENTIFICATION (ID_CONNECTION, ROLE, LOGIN_CONNECTION, PSEUDO_CONNECTION, MOT_PASSE, NO_ENSEIGNANT, NO_ETUDIANT) VALUES (23, 'ADM', 'psaliou@univ-brest.fr', 'psaliou', 'dosi', '1', null);