--
--  Création du jeu d'essai de la table ETUDIANT
--



Insert into   ETUDIANT (NO_ETUDIANT,CODE_FORMATION,ANNEE_UNIVERSITAIRE,NOM,PRENOM,SEXE,DATE_NAISSANCE,LIEU_NAISSANCE,NATIONALITE,TELEPHONE,MOBILE,EMAIL,EMAIL_UBO,ADRESSE,CODE_POSTAL,VILLE,PAYS_ORIGINE,UNIVERSITE_ORIGINE,GROUPE_TP,GROUPE_ANGLAIS) values ('21406398','M2DOSI','2023-2024','EL HEDDADI','Mohamed','M',to_date('05/05/00','DD/MM/RR'),'Houcima','Marocaine',null,'07 61 49 42 29','mohamed.elheddadi@gmail.com','mohamed.elheddadi@univ-brest.fr','2 rue des Archives','29287','BREST','MA','ENSA','1','1');

Insert into   ETUDIANT (NO_ETUDIANT,CODE_FORMATION,ANNEE_UNIVERSITAIRE,NOM,PRENOM,SEXE,DATE_NAISSANCE,LIEU_NAISSANCE,NATIONALITE,TELEPHONE,MOBILE,EMAIL,EMAIL_UBO,ADRESSE,CODE_POSTAL,VILLE,PAYS_ORIGINE,UNIVERSITE_ORIGINE,GROUPE_TP,GROUPE_ANGLAIS) values ('21406849','M2DOSI','2023-2024','CH','Hamza','M',to_date('05/05/96','DD/MM/RR'),'Sefrou','Marocaine',null,'06 64 02 43 05','hamzach@gmail.com','hamzach@univ-brest.fr','2 rue des Archives','29287','BREST','MA','ENIM','1','1');

Insert into   ETUDIANT (NO_ETUDIANT,CODE_FORMATION,ANNEE_UNIVERSITAIRE,NOM,PRENOM,SEXE,DATE_NAISSANCE,LIEU_NAISSANCE,NATIONALITE,TELEPHONE,MOBILE,EMAIL,EMAIL_UBO,ADRESSE,CODE_POSTAL,VILLE,PAYS_ORIGINE,UNIVERSITE_ORIGINE,GROUPE_TP,GROUPE_ANGLAIS) values ('21406939','M2DOSI','2023-2024','SAIDI','Israe','F',to_date('05/05/01','DD/MM/RR'),'Tanger','Marocaine',null,'06 61 85 47 53','israesaidi@gmail.com','israesaidi@univ-brest.fr','2 rue des Archives','29287','BREST','MA','FST','1','1');


