--
--  Création du jeu d'essai de la table PROMOTION
--


Insert into PROMOTION (CODE_FORMATION,ANNEE_UNIVERSITAIRE,NO_ENSEIGNANT,SIGLE_PROMOTION,NB_MAX_ETUDIANT,DATE_REPONSE_LP,DATE_REPONSE_LALP,DATE_RENTREE,LIEU_RENTREE,PROCESSUS_STAGE,COMMENTAIRE) values ('M2DOSI','2023-2024','1','DOSI14','26',to_date('28/02/24','DD/MM/RR'),to_date('10/02/24','DD/MM/RR'),to_date('28/03/24','DD/MM/RR'),'LC117A','PFE',null);
